import csv
import json
import os
import xml.etree.ElementTree as ET
from datetime import datetime
from xml.dom import minidom

from ldapmap_attacker.lib.logger import setup_logger

logger = setup_logger()


class DataExporter:
    def __init__(self, output_dir="./output"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def _resolve_filename(self, filename, extension):
        if filename:
            return filename
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        return "ldap_dump_" + ts + "." + extension

    def export_json(self, records, filename=None):
        filepath = os.path.join(self.output_dir, self._resolve_filename(filename, "json"))
        document = {
            "meta": {
                "generated_at": datetime.now().isoformat(),
                "tool": "ldapmap",
                "record_count": len(records),
            },
            "records": records,
        }

        with open(filepath, "w", encoding="utf-8") as handle:
            json.dump(document, handle, indent=2)

        logger.success(f"JSON export written to {filepath}")
        return filepath

    def export_csv(self, records, filename=None):
        filepath = os.path.join(self.output_dir, self._resolve_filename(filename, "csv"))

        with open(filepath, "w", newline="", encoding="utf-8") as handle:
            if not records:
                handle.write("empty\n")
                logger.warning(f"CSV export created with no records at {filepath}")
                return filepath

            columns = sorted({field for record in records for field in record.keys()})
            writer = csv.DictWriter(handle, fieldnames=columns)
            writer.writeheader()
            writer.writerows(records)

        logger.success(f"CSV export written to {filepath}")
        return filepath

    def export_xml(self, records, filename=None):
        filepath = os.path.join(self.output_dir, self._resolve_filename(filename, "xml"))

        root = ET.Element("ldap_dump")
        metadata = ET.SubElement(root, "metadata")
        ET.SubElement(metadata, "generated_at").text = datetime.now().isoformat()
        ET.SubElement(metadata, "tool").text = "ldapmap"
        ET.SubElement(metadata, "record_count").text = str(len(records))

        entries_element = ET.SubElement(root, "records")
        for record in records:
            entry_element = ET.SubElement(entries_element, "record")
            for field_name, field_value in record.items():
                child = ET.SubElement(entry_element, field_name)
                if isinstance(field_value, list):
                    child.text = ",".join(str(value) for value in field_value)
                else:
                    child.text = str(field_value) if field_value is not None else ""

        xml_text = ET.tostring(root, encoding="unicode")
        pretty_xml = minidom.parseString(xml_text).toprettyxml(indent="  ")
        with open(filepath, "w", encoding="utf-8") as handle:
            handle.write(pretty_xml)

        logger.success(f"XML export written to {filepath}")
        return filepath

    def export_all(self, records, base_filename=None):
        if base_filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            base_filename = f"ldap_dump_{timestamp}"

        return {
            "json": self.export_json(records, f"{base_filename}.json"),
            "csv": self.export_csv(records, f"{base_filename}.csv"),
            "xml": self.export_xml(records, f"{base_filename}.xml"),
        }

    def export_nmap(self, records, filename=None):
        filepath = os.path.join(self.output_dir, self._resolve_filename(filename, "nmap"))

        with open(filepath, "w", encoding="utf-8") as handle:
            handle.write("# nmap style dump\n")
            handle.write("# generated by ldapmap\n\n")

            for record in records:
                uid = record.get("uid", "unknown")
                cn = record.get("cn", "unknown")
                mail = record.get("mail", "")
                department = record.get("ou", "")
                handle.write(f"Host: {uid} ({cn})\n")
                if mail:
                    handle.write(f"Mail: {mail}\n")
                if department:
                    handle.write(f"Department: {department}\n")
                handle.write("\n")

        logger.success(f"Nmap-style export written to {filepath}")
        return filepath

    def write_json_dump(self, records, fname=None):
        return self.export_json(records, fname)

    def write_csv_dump(self, records, fname=None):
        return self.export_csv(records, fname)

    def write_xml_dump(self, records, fname=None):
        return self.export_xml(records, fname)

    def dump_all_formats(self, records, base_name=None):
        return self.export_all(records, base_name)

    def make_nmap_style(self, records, fname=None):
        return self.export_nmap(records, fname)


DumpWriter = DataExporter
